### ISSUE TITLE
using pico-png as IP core with xilinx zynq and dma

### ISSUE THREAD

**Issue by geimel** [marph91/pico-png#4]
Hi,
thank you for sharing this great project.

**Comment by marph91** [comment]
Hi @geimel,
thanks for trying it out :)
Actually I didn't implement it on any FPGA yet and only simulated it for now. Did it work for you?

**Comment by geimel** [comment]
I have made a few changes and in simulation with a 10x10 RGB image the results are good. But in the implemeted design the output header is valid, but the image is black.

**Comment by marph91** [comment]
Did you try to run it with a 100 MHz clock? In the readme 100 MHz is written, but when doing synthesis and P&R for a lattice board, only 70 MHz is possible. This might be an issue.

**Comment by geimel** [comment]
The clock is only 62.5MHz

**Comment by geimel** [comment]
I've done some further simulation with a real image.
In behavioral simulation the result is ok. 
But in post-synthesis-functional simulation the result is bullshit, but the header is ok,
post-synthesis-timing simulation give no result because of no interaction on the interface (osl_rdy, osl_valid never go high)

**Comment by marph91** [comment]
Unfortunately, I lack experience with post synthesis simulation. It might be possible with the toolchain I use (ghdl + yosys). If I have time, I will look into it and tell you if there are the same problems.
